apiVersion: run.tanzu.vmware.com/v1alpha1    
kind: TanzuKubernetesCluster                 
metadata:
  name: tkgs2-spring-dev-k8s-1     
  namespace: tkgs2-spring-dev-team-ns
spec:
  distribution:
    version: v1.20  #Resolves to the latest v1.20 image
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: guaranteed-medium                 #vmclass for control plane nodes
      storageClass: standard         #storageclass for control plane
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 30Gi 
    workers:
      count: 2                                 #number of worker nodes
      class: guaranteed-large                 #vmclass for worker nodes
      storageClass: standard         #storageclass for worker nodes
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 300Gi       
  settings:
    network:
      cni:
        name: antrea 
      services:
        cidrBlocks: ["198.101.0.0/16"]        #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.1.0.0/16"]           #Cannot overlap with Supervisor Cluster
    storage:
      classes: ["standard"]              #Named PVC storage classes
      defaultClass: standard   #Default PVC storage class
